name: Something
author: Nothing
url: https://huanchaochen.github.io
baseurl: 
resume_site: https://huanchaochen.github.io
description: Something about Nothing
github_username: huanchaochen
github: https://github.com/huanchaochen
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : xxx
    clientSecret : xxx
    repo : huanchaochen.github.io
    owner : huanchaochen
    admin : huanchaochen
